Logits selection method fixed
singnet/cancer pull request #54
Opened 2020-09-18 07:45 UTC by yashenkoxciv

2020-09-18 07:49 UTC, noskill commented on ml/curatedBreastData-InfoGAN/xstudy_test.py
> +    train_logits = all_train_logits[:, 1]
Good, but what about xgboost evalation?

2020-09-18 08:35 UTC, noskill requested changes

2020-09-18 08:35 UTC, noskill commented on ml/curatedBreastData-InfoGAN/xstudy_test.py
> +    train_logits = all_train_logits[:, 1]
there is bug in the code below:
test_auc = roc_auc_score(test_predictions, test_logits),

should be

test_auc = roc_auc_score(test_y, test_logits)

2020-09-21 15:41 UTC, merged

2020-09-21 15:41 UTC, mjsduncan commented
thanks, @yashenkoxciv !